[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirection pour les erreurs 404 (optionnel)
[[redirects]]
  from = "/404.html"
  to = "/index.html"
  status = 200